#!/usr/bin/env bash
./launch_tests.sh qmix
./launch_tests_duo.sh qmix
./launch_tests.sh coma
./launch_tests_duo.sh coma
./launch_tests.sh iql
./launch_tests_duo.sh iql
./launch_tests.sh iac
./launch_tests_duo.sh iac
./launch_tests.sh maven
./launch_tests_duo.sh maven