
# --- IQL specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode_multi"
batch_size_run: 1

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "q_learner_multi"
double_q: True
mixer: # Mixer becomes None

name: "iql_smac_multiple_test"


mac: "multi_mac"

use_cuda: False
checkpoint_path: "results/models/iql_smac_multiple__2019-04-08_14-42-19/" # Load a checkpoint from this path
