# --- QMIX specific parameters ---
# --- This config file uses the episodic runner, which is useful for testing locally ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode_multi"
batch_size_run: 1


buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "q_learner_multi"
double_q: True
mixer: "qmix_multi"
mixing_embed_dim: 32

name: "qmix_multi_parallel_test"
mac: "multi_mac"
use_cuda: False

save_model_interval: 20000
save_model: True # Save the models to disk

checkpoint_path: "../results/models/qmix_close__2019-04-17_15-15-01/" # Load a checkpoint from this path
n_epsiode_per_test: 1
n_skip: 3 # Skip "n_skip" networks each iteration