# --- QMIX specific parameters ---
# --- This config file uses the episodic runner, which is useful for testing locally ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 0.5
epsilon_finish: 0.05
epsilon_anneal_time: 50000
use_tensorboard: True

runner: "episode"
batch_size_run: 1

buffer_size: 5000
# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "v_learner"
double_q: False
mixer: "vmix"
mixing_embed_dim: 32

name: "vmix"
